CREATE TYPE meeting_status AS ENUM (
  'SCHEDULED',
  'CONFIRMED',
  'IN_PROGRESS',
  'COMPLETED',
  'CANCELLED'
);

CREATE TYPE meeting_type AS ENUM (
  'PHYSICAL',
  'VIRTUAL'
);

CREATE TYPE notification_type AS ENUM (
  'MESSAGE',
  'EMAIL'
);

CREATE TYPE audit_log_action_types AS ENUM (
  'INSERT',
  'UPDATE',
  'DELETE',
  'FETCH'
);

CREATE TABLE roles (
  id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        VARCHAR(50)  UNIQUE NOT NULL,
  description VARCHAR(255),
  created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE  roles      IS 'System user roles';
COMMENT ON COLUMN roles.name IS 'Role name: admin, staff, tutor, student';

CREATE TABLE permissions (
  id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resource    VARCHAR(100) UNIQUE NOT NULL,
  description VARCHAR(255),
  created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE permissions IS 'System permissions for role-based access control';

CREATE TABLE users (
  id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username      VARCHAR(50)  UNIQUE NOT NULL,
  email         VARCHAR(254) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  first_name    VARCHAR(150) NOT NULL,
  last_name     VARCHAR(150) NOT NULL,
  role_id       INT          NOT NULL,
  is_logged_in  BOOLEAN      NOT NULL DEFAULT true,
  created_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE users IS 'System users with role-based access';

CREATE TABLE role_permissions (
  id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role_id       INT         NOT NULL,
  permission_id INT         NOT NULL,
  granted_by    INT         NOT NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE tutor_students (
  id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tutor_id     INT         NOT NULL,
  student_id   INT         NOT NULL,
  allocated_by INT         NOT NULL,
  notes        TEXT,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_tutor_not_student CHECK (tutor_id <> student_id)
);

COMMENT ON TABLE tutor_students IS 'Tutor-student allocations with complete history';

CREATE TABLE messages (
  id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_id    INT         NOT NULL,
  recipient_id INT         NOT NULL,
  subject      VARCHAR(200),
  body         TEXT        NOT NULL,
  is_read      BOOLEAN     NOT NULL DEFAULT false,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_message_different_users CHECK (sender_id <> recipient_id),
  CONSTRAINT chk_message_body            CHECK (char_length(body) > 0 AND char_length(body) <= 10000)
);

COMMENT ON TABLE messages IS 'User-to-user messages within tutoring context';

CREATE TABLE meetings (
  id                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scheduled_by        INT            NOT NULL,
  scheduled_at        TIMESTAMPTZ    NOT NULL,
  duration_minutes    INTEGER        NOT NULL DEFAULT 60,
  meeting_type        meeting_type   NOT NULL,
  meeting_link        VARCHAR(500),
  agenda              TEXT,
  notes               TEXT,
  status              meeting_status NOT NULL,
  cancellation_reason TEXT,
  created_at          TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
  updated_at          TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_meeting_duration CHECK (duration_minutes BETWEEN 15 AND 480),
  CONSTRAINT chk_meeting_future   CHECK (scheduled_at > NOW() - INTERVAL '1 hour')
);

COMMENT ON TABLE  meetings                  IS 'Scheduled tutoring sessions';
COMMENT ON COLUMN meetings.duration_minutes IS 'Between 15 and 480';

CREATE TABLE documents (
  id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  allocation_id   INT          NOT NULL,
  uploaded_by     INT          NOT NULL,
  filename        VARCHAR(255) NOT NULL,
  file_path       VARCHAR(500) NOT NULL,
  file_size_bytes BIGINT       NOT NULL,
  mime_type       VARCHAR(100) NOT NULL,
  description     TEXT,
  created_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_file_size_positive CHECK (file_size_bytes > 0),
  CONSTRAINT chk_file_size_max      CHECK (file_size_bytes <= 104857600)
);

COMMENT ON TABLE documents IS 'Shared documents and resources for tutoring sessions';

CREATE TABLE document_comments (
  id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_id INT         NOT NULL,
  author_id   INT         NOT NULL,
  body        TEXT        NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_doc_comment_body CHECK (char_length(body) > 0 AND char_length(body) <= 2000)
);

COMMENT ON TABLE document_comments IS 'Comments on shared documents';

CREATE TABLE blog_posts (
  id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  author_id  INT          NOT NULL,
  title      VARCHAR(300) NOT NULL,
  body       TEXT         NOT NULL,
  created_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE blog_posts IS 'Knowledge base articles and announcements';

CREATE TABLE blog_comments (
  id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id    INT         NOT NULL,
  author_id  INT         NOT NULL,
  body       TEXT        NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_blog_comment_body CHECK (char_length(body) > 0 AND char_length(body) <= 2000)
);

COMMENT ON TABLE blog_comments IS 'Comments on blog posts';

CREATE TABLE notifications (
  id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    INT               NOT NULL,
  type       notification_type NOT NULL,
  title      VARCHAR(200)      NOT NULL,
  message    TEXT              NOT NULL,
  created_at TIMESTAMPTZ       NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ       NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE notifications IS 'User notifications for system events';

CREATE TABLE audit_logs (
  id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  table_name VARCHAR(50)             NOT NULL,
  record_id  INT                     NOT NULL,
  action     audit_log_action_types  NOT NULL,
  old_data   JSONB,
  new_data   JSONB,
  changed_by INT,
  created_at TIMESTAMPTZ             NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ             NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE audit_logs IS 'Comprehensive audit trail for compliance';

ALTER TABLE role_permissions  ADD FOREIGN KEY (role_id)       REFERENCES roles (id)          ON DELETE CASCADE  DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE role_permissions  ADD FOREIGN KEY (permission_id) REFERENCES permissions (id)    ON DELETE CASCADE  DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE role_permissions  ADD FOREIGN KEY (granted_by)    REFERENCES users (id)          ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE users             ADD FOREIGN KEY (role_id)       REFERENCES roles (id)          ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE tutor_students    ADD FOREIGN KEY (tutor_id)      REFERENCES users (id)          ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE tutor_students    ADD FOREIGN KEY (student_id)    REFERENCES users (id)          ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE tutor_students    ADD FOREIGN KEY (allocated_by)  REFERENCES users (id)          ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE messages          ADD FOREIGN KEY (sender_id)     REFERENCES users (id)          ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE messages          ADD FOREIGN KEY (recipient_id)  REFERENCES users (id)          ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE meetings          ADD FOREIGN KEY (scheduled_by)  REFERENCES users (id)          ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE documents         ADD FOREIGN KEY (allocation_id) REFERENCES tutor_students (id) ON DELETE CASCADE  DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE documents         ADD FOREIGN KEY (uploaded_by)   REFERENCES users (id)          ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE document_comments ADD FOREIGN KEY (document_id)  REFERENCES documents (id)      ON DELETE CASCADE  DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE document_comments ADD FOREIGN KEY (author_id)    REFERENCES users (id)          ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE blog_posts        ADD FOREIGN KEY (author_id)     REFERENCES users (id)          ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE blog_comments     ADD FOREIGN KEY (post_id)       REFERENCES blog_posts (id)     ON DELETE CASCADE  DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE blog_comments     ADD FOREIGN KEY (author_id)     REFERENCES users (id)          ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE notifications     ADD FOREIGN KEY (user_id)       REFERENCES users (id)          ON DELETE CASCADE  DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE audit_logs        ADD FOREIGN KEY (changed_by)    REFERENCES users (id)          ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

CREATE INDEX ON roles             (name);
CREATE INDEX ON permissions       (resource);
CREATE INDEX ON role_permissions  (role_id, permission_id, granted_by);
CREATE INDEX ON users             (email);
CREATE INDEX ON users             (first_name);
CREATE INDEX ON users             (last_name);
CREATE INDEX ON users             (username);
CREATE INDEX ON users             (role_id);
CREATE INDEX ON users             (is_logged_in);
CREATE INDEX ON tutor_students    (tutor_id);
CREATE INDEX ON tutor_students    (student_id);
CREATE INDEX ON tutor_students    (tutor_id, student_id);
CREATE INDEX ON messages          (sender_id, recipient_id, subject, is_read);
CREATE INDEX ON meetings          (scheduled_at);
CREATE INDEX ON meetings          (status);
CREATE INDEX ON meetings          (scheduled_by);
CREATE INDEX ON documents         (allocation_id);
CREATE INDEX ON documents         (uploaded_by);
CREATE INDEX ON document_comments (document_id);
CREATE INDEX ON document_comments (author_id);
CREATE INDEX ON blog_posts        (author_id);
CREATE INDEX ON blog_posts        (title);
CREATE INDEX ON blog_comments     (post_id);
CREATE INDEX ON blog_comments     (author_id);
CREATE INDEX ON notifications     (type, created_at);
CREATE INDEX ON notifications     (user_id);
CREATE INDEX ON audit_logs        (table_name, record_id);
CREATE INDEX ON audit_logs        (changed_by, created_at);
CREATE INDEX ON audit_logs        (created_at);
